POST  https://qr.mmoney.la/test/generateQR HTTP/1.1
Content-Type: application/json
mmoney-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidGVzdCIsImlhdCI6MTY2NTU1ODIxNywiZXhwIjoxNjY1NTY1NDE3fQ.DUK_zx3TJxR2ufTZsyysC9fRB2FhjHDjcqIsfSSGa6k

{
    "transactionID":"202209061229011001",
    "phonenumber" : "2055220199",
    "amount" : "50000"
}