### ***** update version flow ***** ###
### build GUI
### zip www folder and copy to server public folder
### send http to deploy API
### send http to stop-deploy

POST http://laoapps.com:9006/zdm8-version/mmoney/deploy HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNpZ25hdHVyZSI6IjA0OTUzM2EwNmU3NjNkMzczYTVkMDZjNTZjOTYxOGM4OTI2ZGE2NTIyMDUzMGE3YmY0M2MxYzQ5MDIzNzg3MWJiZDc1NDNiZGJiODA4OWYwNzNiZTg3MzJkNGZmZDViOGZmYmQ0ODE5YTgyNWMyODE4ZmZjNzQ1ZTIzM2M1YzVlOTMiLCJwaG9uZU51bWJlciI6Iis4NTYyMDU2MzgxMDA5IiwidXVpZCI6Ijk4YzViZDQwLWUzNTMtMTFlZC1hYWQ3LTE1OWIxZjAyMzFmYiIsImlwIjoiMTM5LjUuMTU5LjY3IiwibWFjaGluZSI6IndpbmRvd3MiLCJvdGhlcmluZm8iOiJsYW9hcHAuY29tIiwibG9jYXRpb24iOiJ2aWVudGlhbmUifSwiaWF0IjoxNjk0NDE4MTM3LCJleHAiOjM2MDAwMDAxNjk0NDE4MTM2fQ.VsdDfJWnhYx3Ep5yegv_TTFmWKu8qjZaw5RtBYRf6Nc"
}

###
POST http://laoapps.com:9006/zdm8-version/mmoney/stop-deploy HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNpZ25hdHVyZSI6IjA0OTUzM2EwNmU3NjNkMzczYTVkMDZjNTZjOTYxOGM4OTI2ZGE2NTIyMDUzMGE3YmY0M2MxYzQ5MDIzNzg3MWJiZDc1NDNiZGJiODA4OWYwNzNiZTg3MzJkNGZmZDViOGZmYmQ0ODE5YTgyNWMyODE4ZmZjNzQ1ZTIzM2M1YzVlOTMiLCJwaG9uZU51bWJlciI6Iis4NTYyMDU2MzgxMDA5IiwidXVpZCI6Ijk4YzViZDQwLWUzNTMtMTFlZC1hYWQ3LTE1OWIxZjAyMzFmYiIsImlwIjoiMTM5LjUuMTU5LjY3IiwibWFjaGluZSI6IndpbmRvd3MiLCJvdGhlcmluZm8iOiJsYW9hcHAuY29tIiwibG9jYXRpb24iOiJ2aWVudGlhbmUifSwiaWF0IjoxNjk0NDE4MTM3LCJleHAiOjM2MDAwMDAxNjk0NDE4MTM2fQ.VsdDfJWnhYx3Ep5yegv_TTFmWKu8qjZaw5RtBYRf6Nc"
}



###Report Drop
POST https://vendingserviceapi.laoapps.com/zdm8/loadVendingMachineDropPositionReport HTTP/1.1
Content-Type: application/json

{"fromDate":"2025-04-09","toDate":"2025-04-09","machineId":"11115010","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNpZ25hdHVyZSI6IjA0OTUzM2EwNmU3NjNkMzczYTVkMDZjNTZjOTYxOGM4OTI2ZGE2NTIyMDUzMGE3YmY0M2MxYzQ5MDIzNzg3MWJiZDc1NDNiZGJiODA4OWYwNzNiZTg3MzJkNGZmZDViOGZmYmQ0ODE5YTgyNWMyODE4ZmZjNzQ1ZTIzM2M1YzVlOTMiLCJwaG9uZU51bWJlciI6Iis4NTYyMDU2MzgxMDA5IiwidXVpZCI6Ijk4YzViZDQwLWUzNTMtMTFlZC1hYWQ3LTE1OWIxZjAyMzFmYiIsImlwIjoiMTkyLjE2OC44OC44MSIsIm1hY2hpbmUiOiJ3aW5kb3dzIiwib3RoZXJpbmZvIjoibGFvYXBwLmNvbSIsImxvY2F0aW9uIjoidmllbnRpYW5lIn0sImlhdCI6MTc0NDE3MTgzMSwiZXhwIjozNjAwMDAwMTc0NDE3MTgzMH0.lZV7q0gB-3jdicBsFzn0wgGWYN8QdUec4Hb1tbmOZJs"}



###
POST https://vendingserviceapi.laoapps.com/zdm8/setAdminControl HTTP/1.1
Content-Type: application/json

{
    "isActive":"",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNpZ25hdHVyZSI6IjA0OTJkNzNmNzRiMDQ1NjMxNGYxNGQ0OGU2ZjBiOTQwOTcyMTBlNGI2MGI0ZDcyMWM4M2E0NDMxOGJjMjgwNTQ2MGI5ZDVmMThjMTc4ZDVhN2QxMzdkNmVjYTI5MmYwNDk2NzAyYzg3NzYzMTU3ZGVmMmE2ZDQxNGEyMDI5ZjRkMjAiLCJwaG9uZU51bWJlciI6Iis4NTYyMDc5OTc5OTk3IiwidXVpZCI6ImFlNmVmNDgwLTBlMTMtMTFmMC04YmViLTk1Y2JkNDYxMTBlOSIsImlwIjoiMTkyLjE2OC44OC44MSIsIm1hY2hpbmUiOiJ3aW5kb3dzIiwib3RoZXJpbmZvIjoibGFvYXBwLmNvbSIsImxvY2F0aW9uIjoidmllbnRpYW5lIn0sImlhdCI6MTc0NTk5NDQ0MCwiZXhwIjozNjAwMDAwMTc0NTk5NDQ0MH0.N-YA6V9dTMC02pROx6DmiPqXR9TIAGoaE0MyuwExO8Y"
}


###
POST https://tvending4.khamvong.com/zdm8/validateHMVending HTTP/1.1
Content-Type: application/json

{
    "token":"79f7928f3deb7436d6e110dfae37e8f80ea9c65f55ea84eb449895b63bc5909e"
}

###
POST https://tvending4.khamvong.com/zdm8/openstock HTTP/1.1
Content-Type: application/json

{
    "machineToken":"79f7928f3deb7436d6e110dfae37e8f80ea9c65f55ea84eb449895b63bc5909e",
    "secret":"28048257534dfe7bf3d3be02b4026b6ef0ed65d6e605c40bfea635f5e7bbc1cc",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNpZ25hdHVyZSI6IjA0OTUzM2EwNmU3NjNkMzczYTVkMDZjNTZjOTYxOGM4OTI2ZGE2NTIyMDUzMGE3YmY0M2MxYzQ5MDIzNzg3MWJiZDc1NDNiZGJiODA4OWYwNzNiZTg3MzJkNGZmZDViOGZmYmQ0ODE5YTgyNWMyODE4ZmZjNzQ1ZTIzM2M1YzVlOTMiLCJwaG9uZU51bWJlciI6Iis4NTYyMDU2MzgxMDA5IiwidXVpZCI6Ijk4YzViZDQwLWUzNTMtMTFlZC1hYWQ3LTE1OWIxZjAyMzFmYiIsImlwIjoiMTkyLjE2OC44OC44MSIsIm1hY2hpbmUiOiJ3aW5kb3dzIiwib3RoZXJpbmZvIjoibGFvYXBwLmNvbSIsImxvY2F0aW9uIjoidmllbnRpYW5lIn0sImlhdCI6MTc1NTU4Mjg3NywiZXhwIjozNjAwMDAwMTc1NTU4Mjg3Nn0.Hw2aaSrUHsVBwxzk3n6cR7NTJEEKGG05dWyxcmO7-VA"
}


###
POST https://tvending4.khamvong.com/zdm8/getPaidBills HTTP/1.1
Content-Type: application/json

{
    "token":"79f7928f3deb7436d6e110dfae37e8f80ea9c65f55ea84eb449895b63bc5909e"

}

###
POST https://tvending4.khamvong.com/zdm8/reportBillNotPaid HTTP/1.1
Content-Type: application/json

{
    "ownerUuid":"98c5bd40-e353-11ed-aad7-159b1f0231fb",
    "machineId":"11111111",
    "fromDate":"2025-04-09",
    "toDate":"2025-05-09",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNpZ25hdHVyZSI6IjA0OTJkNzNmNzRiMDQ1NjMxNGYxNGQ0OGU2ZjBiOTQwOTcyMTBlNGI2MGI0ZDcyMWM4M2E0NDMxOGJjMjgwNTQ2MGI5ZDVmMThjMTc4ZDVhN2QxMzdkNmVjYTI5MmYwNDk2NzAyYzg3NzYzMTU3ZGVmMmE2ZDQxNGEyMDI5ZjRkMjAiLCJwaG9uZU51bWJlciI6Iis4NTYyMDc5OTc5OTk3IiwidXVpZCI6ImFlNmVmNDgwLTBlMTMtMTFmMC04YmViLTk1Y2JkNDYxMTBlOSIsImlwIjoiMTkyLjE2OC44OC44MSIsIm1hY2hpbmUiOiJ3aW5kb3dzIiwib3RoZXJpbmZvIjoibGFvYXBwLmNvbSIsImxvY2F0aW9uIjoidmllbnRpYW5lIn0sImlhdCI6MTc0NTk5NDQ0MCwiZXhwIjozNjAwMDAwMTc0NTk5NDQ0MH0.N-YA6V9dTMC02pROx6DmiPqXR9TIAGoaE0MyuwExO8Y"
}


###
POST https://vending-service-api5.laoapps.com/zdm8/reportClientLog HTTP/1.1
Content-Type: application/json

{
    "machineId":"77755001",
    "fromDate":"2025-09-15",
    "toDate":"2025-09-30",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNpZ25hdHVyZSI6IjA0OTUzM2EwNmU3NjNkMzczYTVkMDZjNTZjOTYxOGM4OTI2ZGE2NTIyMDUzMGE3YmY0M2MxYzQ5MDIzNzg3MWJiZDc1NDNiZGJiODA4OWYwNzNiZTg3MzJkNGZmZDViOGZmYmQ0ODE5YTgyNWMyODE4ZmZjNzQ1ZTIzM2M1YzVlOTMiLCJwaG9uZU51bWJlciI6Iis4NTYyMDU2MzgxMDA5IiwidXVpZCI6Ijk4YzViZDQwLWUzNTMtMTFlZC1hYWQ3LTE1OWIxZjAyMzFmYiIsImlwIjoiMTkyLjE2OC44OC44MSIsIm1hY2hpbmUiOiJ3aW5kb3dzIiwib3RoZXJpbmZvIjoibGFvYXBwLmNvbSIsImxvY2F0aW9uIjoidmllbnRpYW5lIn0sImlhdCI6MTc0OTI2NzIwNywiZXhwIjozNjAwMDAwMTc0OTI2NzIxMH0.GpcrN08ZtwKzbguAV3EDtRKC45KM4OfNgfyv5S4A3iE"
}


###
POST https://vending-service-api5.laoapps.com/zdm8/reportLogsTemp HTTP/1.1
Content-Type: application/json

{
    "machineId":"77755001",
    "fromDate":"2025-09-15",
    "toDate":"2025-09-30",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNpZ25hdHVyZSI6IjA0OTUzM2EwNmU3NjNkMzczYTVkMDZjNTZjOTYxOGM4OTI2ZGE2NTIyMDUzMGE3YmY0M2MxYzQ5MDIzNzg3MWJiZDc1NDNiZGJiODA4OWYwNzNiZTg3MzJkNGZmZDViOGZmYmQ0ODE5YTgyNWMyODE4ZmZjNzQ1ZTIzM2M1YzVlOTMiLCJwaG9uZU51bWJlciI6Iis4NTYyMDU2MzgxMDA5IiwidXVpZCI6Ijk4YzViZDQwLWUzNTMtMTFlZC1hYWQ3LTE1OWIxZjAyMzFmYiIsImlwIjoiMTkyLjE2OC44OC44MSIsIm1hY2hpbmUiOiJ3aW5kb3dzIiwib3RoZXJpbmZvIjoibGFvYXBwLmNvbSIsImxvY2F0aW9uIjoidmllbnRpYW5lIn0sImlhdCI6MTc0OTI2NzIwNywiZXhwIjozNjAwMDAwMTc0OTI2NzIxMH0.GpcrN08ZtwKzbguAV3EDtRKC45KM4OfNgfyv5S4A3iE"
}


###
POST https://tvending4.khamvong.com/zdm8/reportBilling HTTP/1.1
Content-Type: application/json

{

}




###
POST https://vending-service-api5.laoapps.com/zdm8/clearLogsTemp HTTP/1.1
Content-Type: application/json

{


    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNpZ25hdHVyZSI6IjA0OTUzM2EwNmU3NjNkMzczYTVkMDZjNTZjOTYxOGM4OTI2ZGE2NTIyMDUzMGE3YmY0M2MxYzQ5MDIzNzg3MWJiZDc1NDNiZGJiODA4OWYwNzNiZTg3MzJkNGZmZDViOGZmYmQ0ODE5YTgyNWMyODE4ZmZjNzQ1ZTIzM2M1YzVlOTMiLCJwaG9uZU51bWJlciI6Iis4NTYyMDU2MzgxMDA5IiwidXVpZCI6Ijk4YzViZDQwLWUzNTMtMTFlZC1hYWQ3LTE1OWIxZjAyMzFmYiIsImlwIjoiMTkyLjE2OC44OC44MSIsIm1hY2hpbmUiOiJ3aW5kb3dzIiwib3RoZXJpbmZvIjoibGFvYXBwLmNvbSIsImxvY2F0aW9uIjoidmllbnRpYW5lIn0sImlhdCI6MTc0OTI2NzIwNywiZXhwIjozNjAwMDAwMTc0OTI2NzIxMH0.GpcrN08ZtwKzbguAV3EDtRKC45KM4OfNgfyv5S4A3iE"
}

###
POST https://vendingserviceapi.laoapps.com/zdm8/checkPaidMmoney HTTP/1.1
Content-Type: application/json

{
    "transactionID":"202505090758372079979997",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNpZ25hdHVyZSI6IjA0OTJkNzNmNzRiMDQ1NjMxNGYxNGQ0OGU2ZjBiOTQwOTcyMTBlNGI2MGI0ZDcyMWM4M2E0NDMxOGJjMjgwNTQ2MGI5ZDVmMThjMTc4ZDVhN2QxMzdkNmVjYTI5MmYwNDk2NzAyYzg3NzYzMTU3ZGVmMmE2ZDQxNGEyMDI5ZjRkMjAiLCJwaG9uZU51bWJlciI6Iis4NTYyMDc5OTc5OTk3IiwidXVpZCI6ImFlNmVmNDgwLTBlMTMtMTFmMC04YmViLTk1Y2JkNDYxMTBlOSIsImlwIjoiMTkyLjE2OC44OC44MSIsIm1hY2hpbmUiOiJ3aW5kb3dzIiwib3RoZXJpbmZvIjoibGFvYXBwLmNvbSIsImxvY2F0aW9uIjoidmllbnRpYW5lIn0sImlhdCI6MTc0NTk5NDQ0MCwiZXhwIjozNjAwMDAwMTc0NTk5NDQ0MH0.N-YA6V9dTMC02pROx6DmiPqXR9TIAGoaE0MyuwExO8Y"
}