post https://gateway.ltcdev.la/PartnerVending/GetTransIn
Content-Type: application/json
api-key : 69b713d9-6eb2-413c-950e-34c11b8d5de6

{
    "user_id":"2056924465",
    "starDate":"2026-07-14",
    "endDate":"2026-07-15"
}
###
POST https://vending-service-api5.laoapps.com/mmoneyx/mmoneyxRoutes HTTP/1.1
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNpZ25hdHVyZSI6IjA0ZGNjOWZjNDQ5MzhkMTcyMGEwMWQzYmFhNDY3NmRkZjc3ZGZmMjA3ZGU1ZGU0MDg4ZWI4ZWE1MWU1YmE2ZWI2Njc4ZjVjNGUwM2ZjZTBmZWNiNTQ0OTg3NmJiZTk0YTEyYTdjODllZDMyMzYyNjkzZmZmNGYzYTYxZmI5NGM0YjkiLCJwaG9uZU51bWJlciI6Iis4NTYyMDUyNzE3NzA5IiwidXVpZCI6IjA2NTJlNzgwLWYwYTUtMTFlZC04MWNmLWIxYzFkNzBiNzAwMCIsImlwIjoiMTkyLjE2OC44OC44MSIsIm1hY2hpbmUiOiJ3aW5kb3dzIiwib3RoZXJpbmZvIjoibGFvYXBwLmNvbSIsImxvY2F0aW9uIjoidmllbnRpYW5lIn0sImlhdCI6MTc4MTE1MTEyMSwiZXhwIjozNjAwMDAwMTc4MTE1MTEyMH0.okLAjGCa8MeKJLKX_6IsRTMg2Nq_mu0A7SKlP_hejj4

{
    "user_id":"2056924465",
    "starDate":"2026-07-15",
    "endDate":"2026-07-16",
    "secret":"e2f48898-3453-4214-9025-27e905b269d9",
    "shopPhonenumber":"54393141"
}


####
post https://gateway.ltcdev.la/PartnerVending/GetTransOut
Content-Type: application/json
api-key : 69b713d9-6eb2-413c-950e-34c11b8d5de6

{
    "user_id":"2077733201",
    "starDate":"2026-06-1",
    "endDate":"2026-06-2"
}

###
post https://gateway.ltcdev.la/PartnerVending/RegisterMerchant
Content-Type: application/json
api-key : 69b713d9-6eb2-413c-950e-34c11b8d5de6

{
    "requestId":"2077733201",
    "merchantname":"2026-06-1",
    "customername":"2026-06-2",
    "msisdn":"20xxxx",
    "address":"Phongton Chanthabuli, Vientiane"
}

###
get https://gateway.ltcdev.la/PartnerVending/MerchantList
Content-Type: application/json
api-key : 69b713d9-6eb2-413c-950e-34c11b8d5de6